package(default_visibility = ["//visibility:public"])

java_binary(
  name = "main",
  srcs = glob(['*.java']),
  main_class = "org.example.Main",
  deps = [
    "//src/main/java/org/example/library",
  ]
)
